### ISSUE TITLE
subject cartographics mappings need love

### ISSUE THREAD

**Issue by ndushay** [sul-dlss-labs/cocina-descriptive-metadata#104]
You have example 19 https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_subject.txt#L606, which has all of the pieces under the same `cartographics` element.

But we've got data (see below) has it under the same `subject` element, but not under a single `cartographics` element.  I'm also wondering how we marry the "form" data back into the "subject cartographic" data on the cocina-to-fedora mappings, but la la la la.

There are more examples:  druid:dq489rh4342, druid:tr868bk9200, druid:sn347jm4106, druid:jd101tx0857, druid:pk219xq7408, druid:jg212km5908, druid:zw340mq7550, druid:fb929qm5440, druid:ky759jk5188, druid:qw988fw3662 (from sul-dlss/dor-services-app/issues/1267, which were discovered with Justin Littman's validation tool).

(And, yes, these are ooooold map objects that may not have followed the best practices of how to put their info in MODS)

https://argo.stanford.edu/view/dq489rh4342

```xml
 <subject>
    <cartographics>
      <coordinates>W0750700 W0741200 N0443400 N0431200</coordinates>
    </cartographics>
  </subject>
  <subject>
    <cartographics>
      <scale>Scale ca. 1:126,720. 1 in. to 2 miles.</scale>
    </cartographics>
    <cartographics>
      <coordinates>(W 75&#x2070;07&#x2B9;00&#x2B9;--W 74&#x2070;12&#x2B9;00&#x2B9;/N 44&#x2070;34&#x2B9;00&#x2B9;--N 43&#x2070;12&#x2B9;00&#x2B9;)</coordinates>
    </cartographics>
  </subject>
```

https://argo.stanford.edu/view/tr868bk9200

```xml
<subject>
    <cartographics>
      <scale>Scale 1:100,000 :</scale>
    </cartographics>
    <cartographics>
      <projection>universal transverse Mercator proj.</projection>
    </cartographics>
  </subject>
```

https://argo.stanford.edu/view/sn347jm4106

```xml
<subject>
    <cartographics>
      <coordinates>E1283000 E1420000 N0420000 N0310000</coordinates>
    </cartographics>
  </subject>
  <subject>
    <cartographics>
      <scale>Scale 1:50,000</scale>
    </cartographics>
    <cartographics>
      <coordinates>(E 128&#x2070;30&#x2B9;--E 142&#x2070;00&#x2B9;/N 42&#x2070;00&#x2B9;--N 31&#x2070;00&#x2B9;).</coordinates>
    </cartographics>
  </subject>
```

**Comment by arcadiafalcone** [comment]
Refreshing from source will merge the `cartographics` subelements into one, and it's OK for them to come out like that after a round trip. They will still have `coordinates` in two separate `subject` elements because each derives from a different MARC field.
