### ISSUE TITLE
Map frequency

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/cocina-descriptive-metadata#203]
For druid:rc322ch9309:

```
<frequency>Weekly</frequency>
```

Note that this a child of `<mods>`, not `<originInfo>`.

**Comment by arcadiafalcone** [comment]
See https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/3a2405686f54e8ef669474fc538869325714f654/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L1082 and https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/3a2405686f54e8ef669474fc538869325714f654/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L1108.
