### ISSUE TITLE
what should happen to script attribute when there is no altRepGroup?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss-labs/cocina-descriptive-metadata#221]
https://argo.stanford.edu/view/druid:pk167yq6876 has but one originInfo element:

```xml
 <originInfo script="Latn">
    <place>
      <placeTerm type="code" authority="marccountry">ja</placeTerm>
    </place>
    <dateIssued encoding="marc" point="start">1915</dateIssued>
    <dateIssued encoding="marc" point="end">1942</dateIssued>
    <issuance>monographic</issuance>
  </originInfo>
```

it roundtrips like this (no script attribute):

```xml
  <originInfo eventType="publication">
    <dateIssued point="start" encoding="marc">1915</dateIssued>
    <dateIssued point="end" encoding="marc">1942</dateIssued>
    <place>
      <placeTerm type="code" authority="marccountry">ja</placeTerm>
    </place>
    <issuance>monographic</issuance>
  </originInfo>
```

Is it okay if we lose the attribute?  Or should we keep it?   

Whichever way, when this is answered, a dor-services-app mapping ticket needs to be created.

**Comment by arcadiafalcone** [comment]
Script should stay even in the absence of altRepGroup. (I've refreshed that record and the script went away, but it looks like it's only getting originInfo data from the MARC fields and not from the actual 264, so I will need to investigate further to figure out what exactly is going on there.)

**Comment by ndushay** [comment]
sul-dlss/dor-services-app/issues/1683 created with a question -- does this apply to all top level MODS elements?   please answer there and here ...

**Comment by arcadiafalcone** [comment]
Yes, it applies to any instance of the script attribute.

**Comment by ndushay** [comment]
Closing this in favor of sul-dlss/dor-services-app/issues/1683
