### ISSUE TITLE
Parallel date question

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/cocina-descriptive-metadata#234]
`<dateIssued>2005</dateIssued>`
https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L1485

and
`<dateIssued>2005.</dateIssued>`
https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L1494

are mapped to:
```
      "date": [
        {
          "value": "2005"
        }
      ]
```.

Is that correct or is:
```
       +         parallelValue: [
       +           {
       +             value: "2005"
       +           },
       +           {
       +             value: "2005."
       +           }
       +         ]
```
?

**Comment by arcadiafalcone** [comment]
The first is correct - the trailing period should be ignored.
