### ISSUE TITLE
Standardize copyright vs copyright notice for events

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/cocina-descriptive-metadata#236]

**Comment by arcadiafalcone** [comment]
Is this referring to originInfo example 26b? https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/0025be2da5bc401c1205eff7029f2e7892ee3fe9/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L634

**Comment by justinlittman** [comment]
Yes, that appears to be the only place where "copyright notice" appears.
