### ISSUE TITLE
gml:id="ID"

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/cocina-descriptive-metadata#241]
https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/459fbdbab322f2651d129aa6b9ba4c5357f39bb1/mods_cocina_mappings/mods_to_cocina_geo_extension.txt#L8

When this is missing from the original should it be normalized by adding (e.g., druid:dh231pg2883)? Or should it be normalized by removing when present?

**Comment by arcadiafalcone** [comment]
`gml:id="ID"` can be ignored and dropped out in the round trip. I'll need to look at instances of `gml:id` with other values if any come up.
