### ISSUE TITLE
add mods subject classification mapping for no authority

### ISSUE THREAD

**Issue by ndushay** [sul-dlss-labs/cocina-descriptive-metadata#294]
https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb#L120-L142

**Comment by ndushay** [comment]
might I suggest as example 1A ?   Totally up to you, of course.

**Comment by arcadiafalcone** [comment]
<classification> should always have at least one of authority, authorityURI, or valueURI - the value is meaningless without knowing the source.

**Comment by ndushay** [comment]
I gave the wrong link:  it should be https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb#L63-L86

and

https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/to_fedora/descriptive/subject_classification_spec.rb#L63-L86

The important question is whether our rspec code is correct in how it handles this situation (the spec code presumably got written to address something encountered with real data)

**Comment by arcadiafalcone** [comment]
The rspec mappings are correct, but if there is none of `authority`, `authorityURI`, or `valueURI`, it should report an error ("No source given for classification value' or similar)

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/issues/1835 is for adding that warning.

@ndushay OK to close this ticket now?

**Comment by ndushay** [comment]
@justinlittman fine with me to close this;  up to @arcadiafalcone  now.
