### ISSUE TITLE
Are these mappings capable of being bi-directional?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/cocina-descriptive-metadata#40]
https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/07e7b45dbf03f675ea73c99297b26a11ac019b27/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L549-L564

https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/07e7b45dbf03f675ea73c99297b26a11ac019b27/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L566-L581

**Comment by arcadiafalcone** [comment]
I think the line numbers in the links are off because the files have changed - do you remember which examples these were?

**Comment by jcoyne** [comment]
@arcadiafalcone I updated with a commit hash. You should be able to see the case (especially the second) now.

**Comment by arcadiafalcone** [comment]
The first one is roundtrippable (if event type="publication" + untyped date, use dateIssued). I'll update the second.
