### ISSUE TITLE
Event does not support displayLabel

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/cocina-descriptive-metadata#47]
https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_originInfo.txt#L1138

https://github.com/sul-dlss/cocina-models/blob/master/openapi.yml#L676-L707

**Comment by arcadiafalcone** [comment]
Closed by #56
