### ISSUE TITLE
Map MODS geodata extension to appropriate COCINA datastream

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss-labs/cocina-descriptive-metadata#6]
Does coordinate data for geospatial applications still belong in Description, or should it map elsewhere? It needs to be possible for a) data to be generated by MARC2MODS transform and b) data to be added/edited by user, preferably by same mechanism as other descriptive metadata.

**Comment by ndushay** [comment]
I'm afraid I have no idea.

**Comment by jcoyne** [comment]
Is this something different than the iso-19139 formatted metadata?

**Comment by arcadiafalcone** [comment]
This is different - it's metadata originating in MODS (or in MARC converted to MODS), not in ISO 19139.

**Comment by jcoyne** [comment]
@arcadiafalcone In that case I think you can put that in the descriptive schema.

**Comment by arcadiafalcone** [comment]
@jcoyne OK, I'll add them to the mapping.

**Comment by arcadiafalcone** [comment]
Closed by #19
