### ISSUE TITLE
languageOfCataloging primary or not?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/cocina-descriptive-metadata#75]
These seem inconsistent:

https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_recordInfo.txt#L3

https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_recordInfo.txt#L153

**Comment by arcadiafalcone** [comment]
The difference is due to how they were created. The first example is from the replayable spreadsheet, and the modsulator template includes the "primary." The second was converted from MARC, and the XSLT in use at the time did not include the attribute.
