### ISSUE TITLE
Add geo exentionsion schema to description_cocina_schema_v4-4.json

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/cocina-descriptive-metadata#83]
This is blocking completion of https://github.com/sul-dlss/dor-services-app/pull/1163

@arcadiafalcone

**Comment by arcadiafalcone** [comment]
Could you say more about what needs to be added? To my knowledge everything in the geoextension schema is already in the JSON schema.

**Comment by aaron-collier** [comment]
I think we're OK. I was seeing a few errors that I was able to figure out and I believe this was a mistake/misunderstanding of where it was coming from at the time.

Thanks :-)
